#!/bin/bash
echo "=== Supabase SQL Setup Instructions ==="
echo ""
echo "1. Go to your Supabase project dashboard:"
echo "   https://supabase.com/dashboard"
echo ""
echo "2. Click 'SQL Editor' in the left sidebar"
echo ""
echo "3. Copy and paste the contents of 'supabase-schema.sql':"
echo "   /Users/andris811/code/andris811/AVDev/trakt_recap/supabase-schema.sql"
echo ""
echo "4. Click 'Run' to execute the SQL"
echo ""
echo "5. Verify tables were created:"
echo "   - Go to 'Table Editor' to see: watch_history, trakt_stats, content_cache"
echo ""
echo "=== Ready to deploy to Vercel ==="
echo ""
echo "Run these commands:"
echo "  npm install -g vercel"
echo "  vercel login"
echo "  cd /Users/andris811/code/andris811/AVDev/trakt_recap"
echo "  vercel --prod"
